# op-mattermost provides an integration for Mattermost and Open Project.
# Copyright (C) 2020  Girish M

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>

version: "2"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - openproject
      - mattermost
    command: [ "./wait_for_it.sh", "openproject:8080", "--", "npm", "start" ]
  openproject:
    image: "openproject/community:11"
    ports:
    - "8080:8080"
  mattermost:
    image: "mattermost/mattermost-preview"
    ports:
    - "8065:8065"